/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author SrTrojan
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonAgendar = new javax.swing.JButton();
        LabelAgenda = new javax.swing.JLabel();
        CampoAgendamento = new javax.swing.JScrollPane();
        TabelaAgendamento = new javax.swing.JTable();
        LabelObservacao = new javax.swing.JLabel();
        CampoObservacao = new javax.swing.JScrollPane();
        CampoObservacao2 = new javax.swing.JTextArea();
        LabelHora = new javax.swing.JLabel();
        CampoHora = new javax.swing.JTextField();
        LabelData = new javax.swing.JLabel();
        CampoData = new javax.swing.JTextField();
        LabelValor = new javax.swing.JLabel();
        CampoId = new javax.swing.JTextField();
        LabelServico = new javax.swing.JLabel();
        JComboBoxServico = new javax.swing.JComboBox<>();
        LabelCliente = new javax.swing.JLabel();
        JComboBoxCliente = new javax.swing.JComboBox<>();
        LabelId = new javax.swing.JLabel();
        CampoValor = new javax.swing.JTextField();
        DestaqueAgenda = new javax.swing.JLabel();
        FundoAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonAgendar.setBackground(new java.awt.Color(0, 102, 0));
        ButtonAgendar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ButtonAgendar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAgendar.setText("Agendar");
        ButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 480, -1));

        LabelAgenda.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LabelAgenda.setForeground(new java.awt.Color(255, 255, 255));
        LabelAgenda.setText("Agenda");
        getContentPane().add(LabelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 160, -1));

        TabelaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        CampoAgendamento.setViewportView(TabelaAgendamento);

        getContentPane().add(CampoAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 830, 140));

        LabelObservacao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        LabelObservacao.setText("Observação");
        getContentPane().add(LabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 80, -1));

        CampoObservacao2.setColumns(20);
        CampoObservacao2.setRows(5);
        CampoObservacao.setViewportView(CampoObservacao2);

        getContentPane().add(CampoObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 480, 180));

        LabelHora.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelHora.setForeground(new java.awt.Color(255, 255, 255));
        LabelHora.setText("Hora");
        getContentPane().add(LabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 50, -1));
        getContentPane().add(CampoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 270, -1));

        LabelData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelData.setForeground(new java.awt.Color(255, 255, 255));
        LabelData.setText("Data");
        getContentPane().add(LabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 50, -1));
        getContentPane().add(CampoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 270, -1));

        LabelValor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelValor.setForeground(new java.awt.Color(255, 255, 255));
        LabelValor.setText("Valor R$");
        getContentPane().add(LabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 50, -1));

        CampoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIdActionPerformed(evt);
            }
        });
        getContentPane().add(CampoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 270, -1));

        LabelServico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelServico.setForeground(new java.awt.Color(255, 255, 255));
        LabelServico.setText("Servico");
        getContentPane().add(LabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 50, -1));

        JComboBoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBoxServicoItemStateChanged(evt);
            }
        });
        JComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxServicoActionPerformed(evt);
            }
        });
        getContentPane().add(JComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 270, -1));

        LabelCliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        LabelCliente.setText("Cliente");
        getContentPane().add(LabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 40, -1));

        JComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(JComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 270, -1));

        LabelId.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelId.setForeground(new java.awt.Color(255, 255, 255));
        LabelId.setText("Id");
        getContentPane().add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 20, -1));

        CampoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoValorActionPerformed(evt);
            }
        });
        getContentPane().add(CampoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 270, -1));

        DestaqueAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(DestaqueAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 940, 580));

        FundoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(FundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxClienteActionPerformed

    private void ButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendarActionPerformed
        // TODO add your handling code here:
        this.controller.agendar();
    }//GEN-LAST:event_ButtonAgendarActionPerformed

    private void CampoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIdActionPerformed

    private void CampoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoValorActionPerformed

    private void JComboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBoxServicoItemStateChanged
        // TODO add your handling code here:
        this.controller.atualizaValor();
    }//GEN-LAST:event_JComboBoxServicoItemStateChanged

    private void JComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgendar;
    private javax.swing.JScrollPane CampoAgendamento;
    private javax.swing.JTextField CampoData;
    private javax.swing.JTextField CampoHora;
    private javax.swing.JTextField CampoId;
    private javax.swing.JScrollPane CampoObservacao;
    private javax.swing.JTextArea CampoObservacao2;
    private javax.swing.JTextField CampoValor;
    private javax.swing.JLabel DestaqueAgenda;
    private javax.swing.JLabel FundoAgenda;
    private javax.swing.JComboBox<String> JComboBoxCliente;
    private javax.swing.JComboBox<String> JComboBoxServico;
    private javax.swing.JLabel LabelAgenda;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelServico;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JTable TabelaAgendamento;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        this.controller.atualizaValor();
    }

    public JTable getTabelaAgendamento() {
        return TabelaAgendamento;
    }

    public void setTabelaAgendamento(JTable TabelaAgendamento) {
        this.TabelaAgendamento = TabelaAgendamento;
    }

    public JComboBox<String> getJComboBoxCliente() {
        return JComboBoxCliente;
    }

    public void setJComboBoxCliente(JComboBox<String> JComboBoxCliente) {
        this.JComboBoxCliente = JComboBoxCliente;
    }

    public JComboBox<String> getJComboBoxServico() {
        return JComboBoxServico;
    }

    public void setJComboBoxServico(JComboBox<String> JComboBoxServico) {
        this.JComboBoxServico = JComboBoxServico;
    }

    public JTextField getCampoValor() {
        return CampoValor;
    }

    public void setCampoValor(JTextField CampoValor) {
        this.CampoValor = CampoValor;
    }

    public JTextField getCampoData() {
        return CampoData;
    }

    public void setCampoData(JTextField CampoData) {
        this.CampoData = CampoData;
    }

    public JTextField getCampoHora() {
        return CampoHora;
    }

    public void setCampoHora(JTextField CampoHora) {
        this.CampoHora = CampoHora;
    }

    public JTextField getCampoId() {
        return CampoId;
    }

    public void setCampoId(JTextField CampoId) {
        this.CampoId = CampoId;
    }

    public JTextArea getCampoObservacao2() {
        return CampoObservacao2;
    }

    public void setCampoObservacao2(JTextArea CampoObservacao2) {
        this.CampoObservacao2 = CampoObservacao2;
    }
    
    
    
}
