package View;

import Controller.MenuPrincipalController;

/**
 *
 * @author SrTrojan
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoMenuPrincipal = new javax.swing.JLabel();
        BarraMenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        SubMenuCadastro = new javax.swing.JMenuItem();
        SubMenuServiço = new javax.swing.JMenuItem();
        SubMenuUsuario = new javax.swing.JMenuItem();
        MenuOperacao = new javax.swing.JMenu();
        SubMenuCadastro1 = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        SubMenuCadastro2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FundoMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/fundo-MenuPrincipal.jpg"))); // NOI18N
        getContentPane().add(FundoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MenuCadastro.setText("Cadastro");
        MenuCadastro.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        SubMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/cliente-icon.png"))); // NOI18N
        SubMenuCadastro.setText("Cliente");
        MenuCadastro.add(SubMenuCadastro);

        SubMenuServiço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/tesoura-icon.png"))); // NOI18N
        SubMenuServiço.setText("Serviço");
        SubMenuServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuServiçoActionPerformed(evt);
            }
        });
        MenuCadastro.add(SubMenuServiço);

        SubMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/usuario-icon.png"))); // NOI18N
        SubMenuUsuario.setText("Usuario");
        SubMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(SubMenuUsuario);

        BarraMenuPrincipal.add(MenuCadastro);

        MenuOperacao.setText("Operação");
        MenuOperacao.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        SubMenuCadastro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/agenda-icon.png"))); // NOI18N
        SubMenuCadastro1.setText("Agenda");
        SubMenuCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuCadastro1ActionPerformed(evt);
            }
        });
        MenuOperacao.add(SubMenuCadastro1);

        BarraMenuPrincipal.add(MenuOperacao);

        MenuRelatorio.setText("Relatorio");
        MenuRelatorio.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        SubMenuCadastro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/relatorioTrabalho-icon.png"))); // NOI18N
        SubMenuCadastro2.setText("Trabalho");
        MenuRelatorio.add(SubMenuCadastro2);

        BarraMenuPrincipal.add(MenuRelatorio);

        setJMenuBar(BarraMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuServiçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubMenuServiçoActionPerformed

    private void SubMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubMenuUsuarioActionPerformed

    private void SubMenuCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuCadastro1ActionPerformed
        // TODO add your handling code here:
        this.controller.navegarParaAgenda();
    }//GEN-LAST:event_SubMenuCadastro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenuPrincipal;
    private javax.swing.JLabel FundoMenuPrincipal;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuOperacao;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem SubMenuCadastro;
    private javax.swing.JMenuItem SubMenuCadastro1;
    private javax.swing.JMenuItem SubMenuCadastro2;
    private javax.swing.JMenuItem SubMenuServiço;
    private javax.swing.JMenuItem SubMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
